// you can remove this file after backend attached with it or api fetched


export const ALL_JOBS = [
    {
        jobId: 1,
        title: "Forward Security Director",
        company: "Bauch, Schuppe and Schulist Co",
        branchId: "New York",
        location: "New York, USA",
        salary: "$4,000 - $4,200",
        salaryNumeric: 4000,
        type: "Full Time",
        department: "Hotels & Tourism",
        category: "Hotels & Tourism",
        seats: 5,
        description: "Direct and coordinate security activities to safeguard company assets and personnel.",
        posted: "10 mins ago",
        experience: "5+ Years",
        degree: "Master",
        timestamp: Date.now() - 600000
    },
    {
        jobId: 2,
        title: "Regional Creative Facilitator",
        company: "Wisozk - Becker Co",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$3,000 - $3,500",
        salaryNumeric: 3000,
        type: "Part Time",
        department: "Media",
        category: "Media",
        seats: 3,
        description: "Facilitate creative workshops and coordinate regional marketing campaigns.",
        posted: "12 mins ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 720000
    },
    {
        jobId: 3,
        title: "Internal Integration Planner",
        company: "Hauck, Quigley and Feest Inc",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$2,800 - $3,200",
        salaryNumeric: 2800,
        type: "Full Time",
        department: "Construction",
        category: "Construction",
        seats: 2,
        description: "Plan and integrate internal systems for large-scale construction projects.",
        posted: "15 mins ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 900000
    },
    {
        jobId: 4,
        title: "District Intranet Director",
        company: "VonRueden - Weber Co",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$4,200 - $4,800",
        salaryNumeric: 4200,
        type: "Full Time",
        department: "Commerce",
        category: "Commerce",
        seats: 1,
        description: "Oversee the development and maintenance of district-wide intranet services.",
        posted: "24 mins ago",
        experience: "6+ Years",
        degree: "Master",
        timestamp: Date.now() - 1440000
    },
    {
        jobId: 5,
        title: "Corporate Tactics Facilitator",
        company: "Finley Inc",
        branchId: "New York",
        location: "New York, USA",
        salary: "$3,800 - $4,600",
        salaryNumeric: 3800,
        type: "Part Time",
        department: "Commerce",
        category: "Commerce",
        seats: 4,
        description: "Facilitate corporate strategic planning and tactical implementation sessions.",
        posted: "26 mins ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 1500000
    },
    {
        jobId: 6,
        title: "Forward Accounts Consultant",
        company: "Miller Group",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$4,500 - $5,000",
        salaryNumeric: 4500,
        type: "Full Time",
        department: "Financial Services",
        category: "Financial Services",
        seats: 2,
        description: "Consult on forward-looking accounting practices and financial forecasting.",
        posted: "30 mins ago",
        experience: "5+ Years",
        degree: "Master",
        timestamp: Date.now() - 1800000
    },
    {
        jobId: 7,
        title: "Software Engineer",
        company: "Tesla",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$7,000 - $8,500",
        salaryNumeric: 7000,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 10,
        description: "Develop and optimize software systems for electric vehicles and energy products.",
        posted: "1h ago",
        experience: "2+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 3600000
    },
    {
        jobId: 8,
        title: "UX Designer",
        company: "Apple",
        branchId: "New York",
        location: "New York, USA",
        salary: "$6,000 - $7,500",
        salaryNumeric: 6000,
        type: "Freelance",
        department: "Design",
        category: "Design",
        seats: 2,
        description: "Design intuitive and beautiful user experiences for next-generation products.",
        posted: "2h ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 7200000
    },
    {
        jobId: 9,
        title: "Backend Developer",
        company: "Amazon",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$8,000 - $9,500",
        salaryNumeric: 8000,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 8,
        description: "Build scalable and robust backend services for global e-commerce platforms.",
        posted: "3h ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 10800000
    },
    {
        jobId: 10,
        title: "Data Scientist",
        company: "Google",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$9,000 - $11,000",
        salaryNumeric: 9000,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 5,
        description: "Apply advanced machine learning techniques to solve complex data problems.",
        posted: "4h ago",
        experience: "5+ Years",
        degree: "PhD",
        timestamp: Date.now() - 14400000
    },
    {
        jobId: 11,
        title: "Cloud Infrastructure Engineer",
        company: "TechNova Inc",
        branchId: "London",
        location: "London, UK",
        salary: "$6,500 - $8,000",
        salaryNumeric: 6500,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 3,
        description: "Design and maintain secure and scalable cloud infrastructure solutions.",
        posted: "5h ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 18000000
    },
    {
        jobId: 12,
        title: "Marketing Strategist",
        company: "Bright Solutions",
        branchId: "New York",
        location: "New York, USA",
        salary: "$3,500 - $4,200",
        salaryNumeric: 3500,
        type: "Full Time",
        department: "Commerce",
        category: "Commerce",
        seats: 2,
        description: "Develop and execute innovative marketing strategies to drive business growth.",
        posted: "6h ago",
        experience: "2+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 21600000
    },
    {
        jobId: 13,
        title: "Civil Site Engineer",
        company: "BuildCore Ltd",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$4,000 - $5,500",
        salaryNumeric: 4000,
        type: "Full Time",
        department: "Construction",
        category: "Construction",
        seats: 4,
        description: "Supervise site operations and ensure construction projects meet safety standards.",
        posted: "7h ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 25200000
    },
    {
        jobId: 14,
        title: "UI Designer",
        company: "PixelCraft",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$4,500 - $6,000",
        salaryNumeric: 4500,
        type: "Freelance",
        department: "Design",
        category: "Design",
        seats: 1,
        description: "Create visually stunning and user-friendly interfaces for web and mobile apps.",
        posted: "8h ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 28800000
    },
    {
        jobId: 15,
        title: "Tourism Manager",
        company: "TravelEase",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$3,800 - $5,000",
        salaryNumeric: 3800,
        type: "Full Time",
        department: "Hotels & Tourism",
        category: "Hotels & Tourism",
        seats: 2,
        description: "Manage tourism programs and enhance guest experiences at premium locations.",
        posted: "9h ago",
        experience: "5+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 32400000
    },
    {
        jobId: 16,
        title: "Finance Analyst",
        company: "SecureFunds Inc",
        branchId: "London",
        location: "London, UK",
        salary: "$5,000 - $6,500",
        salaryNumeric: 5000,
        type: "Full Time",
        department: "Financial Services",
        category: "Financial Services",
        seats: 3,
        description: "Analyze financial data and provide strategic recommendations for investments.",
        posted: "10h ago",
        experience: "3+ Years",
        degree: "Master",
        timestamp: Date.now() - 36000000
    },
    {
        jobId: 17,
        title: "High School Teacher",
        company: "EduCore Academy",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$2,500 - $3,500",
        salaryNumeric: 2500,
        type: "Full Time",
        department: "Education",
        category: "Education",
        seats: 6,
        description: "Educate and inspire high school students in core academic subjects.",
        posted: "11h ago",
        experience: "2+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 39600000
    },
    {
        jobId: 18,
        title: "Telecom Network Engineer",
        company: "ConnectX",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$5,500 - $7,000",
        salaryNumeric: 5500,
        type: "Full Time",
        department: "Telecommunications",
        category: "Telecommunications",
        seats: 4,
        description: "Design and optimize telecommunications networks for high-speed data transmission.",
        posted: "12h ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 43200000
    },
    {
        jobId: 19,
        title: "Frontend Developer",
        company: "NextGen Labs",
        branchId: "New York",
        location: "New York, USA",
        salary: "$6,000 - $7,500",
        salaryNumeric: 6000,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 5,
        description: "Build responsive and interactive web interfaces using modern technologies.",
        posted: "13h ago",
        experience: "2+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 46800000
    },
    {
        jobId: 20,
        title: "Product Designer",
        company: "Designify",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$5,500 - $7,000",
        salaryNumeric: 5500,
        type: "Full Time",
        department: "Design",
        category: "Design",
        seats: 2,
        description: "Oversee product design cycles from concept to launch for innovative startups.",
        posted: "14h ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 50400000
    },
    {
        jobId: 21,
        title: "Business Development Manager",
        company: "GlobalTrade Co",
        branchId: "London",
        location: "London, UK",
        salary: "$4,500 - $6,000",
        salaryNumeric: 4500,
        type: "Full Time",
        department: "Commerce",
        category: "Commerce",
        seats: 3,
        description: "Identify and pursue new business opportunities in international markets.",
        posted: "15h ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 54000000
    },
    {
        jobId: 22,
        title: "AI Engineer",
        company: "FutureSoft",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$8,000 - $10,000",
        salaryNumeric: 8000,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 4,
        description: "Develop cutting-edge artificial intelligence models for automation and insight.",
        posted: "16h ago",
        experience: "3+ Years",
        degree: "Master",
        timestamp: Date.now() - 57600000
    },
    {
        jobId: 23,
        title: "Site Supervisor",
        company: "Constructify",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$3,800 - $5,200",
        salaryNumeric: 3800,
        type: "Full Time",
        department: "Construction",
        category: "Construction",
        seats: 2,
        description: "Supervise daily site activities and ensure adherence to construction timelines.",
        posted: "17h ago",
        experience: "5+ Years",
        degree: "Diploma",
        timestamp: Date.now() - 61200000
    },
    {
        jobId: 24,
        title: "Graphic Designer",
        company: "Artify Studio",
        branchId: "New York",
        location: "New York, USA",
        salary: "$3,500 - $4,800",
        salaryNumeric: 3500,
        type: "Part Time",
        department: "Design",
        category: "Design",
        seats: 3,
        description: "Create engaging visual content for social media and digital marketing campaigns.",
        posted: "18h ago",
        experience: "2+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 64800000
    },
    {
        jobId: 25,
        title: "Hotel Receptionist",
        company: "StayWell Hotels",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$2,200 - $3,000",
        salaryNumeric: 2200,
        type: "Full Time",
        department: "Hotels & Tourism",
        category: "Hotels & Tourism",
        seats: 5,
        description: "Provide exceptional guest services and manage front-desk operations efficiently.",
        posted: "19h ago",
        experience: "1+ Years",
        degree: "High School",
        timestamp: Date.now() - 68400000
    },
    {
        jobId: 26,
        title: "Accountant",
        company: "FinancePro",
        branchId: "London",
        location: "London, UK",
        salary: "$4,000 - $5,500",
        salaryNumeric: 4000,
        type: "Full Time",
        department: "Financial Services",
        category: "Financial Services",
        seats: 2,
        description: "Manage financial records and ensure compliance with tax regulations.",
        posted: "20h ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 72000000
    },
    {
        jobId: 27,
        title: "School Principal",
        company: "Bright Future School",
        branchId: "Boston",
        location: "Boston, USA",
        salary: "$5,500 - $7,500",
        salaryNumeric: 5500,
        type: "Full Time",
        department: "Education",
        category: "Education",
        seats: 1,
        description: "Lead educational programs and manage school staff for optimal student success.",
        posted: "21h ago",
        experience: "6+ Years",
        degree: "Master",
        timestamp: Date.now() - 75600000
    },
    {
        jobId: 28,
        title: "Telecom Support Specialist",
        company: "NetLink",
        branchId: "Texas",
        location: "Texas, USA",
        salary: "$3,200 - $4,200",
        salaryNumeric: 3200,
        type: "Full Time",
        department: "Telecommunications",
        category: "Telecommunications",
        seats: 8,
        description: "Provide technical support for telecommunications hardware and software issues.",
        posted: "22h ago",
        experience: "2+ Years",
        degree: "Diploma",
        timestamp: Date.now() - 79200000
    },
    {
        jobId: 29,
        title: "DevOps Engineer",
        company: "CloudSync",
        branchId: "New York",
        location: "New York, USA",
        salary: "$7,500 - $9,000",
        salaryNumeric: 7500,
        type: "Full Time",
        department: "Tech",
        category: "Tech",
        seats: 3,
        description: "Automate deployment pipelines and manage cloud-native infrastructure environments.",
        posted: "23h ago",
        experience: "4+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 82800000
    },
    {
        jobId: 30,
        title: "Interior Designer",
        company: "SpaceCraft",
        branchId: "Los Angeles",
        location: "Los Angeles, USA",
        salary: "$4,500 - $6,500",
        salaryNumeric: 4500,
        type: "Freelance",
        department: "Design",
        category: "Design",
        seats: 2,
        description: "Design innovative interior spaces for commercial and residential clients.",
        posted: "1d ago",
        experience: "3+ Years",
        degree: "Bachelor",
        timestamp: Date.now() - 86400000
    }
];

export const CATEGORIES = ['Commerce', 'Tech', 'Design', 'Construction', 'Hotels & Tourism', 'Education', 'Financial Services', 'Media'];
export const BRANCHES = ['New York', 'London', 'Texas', 'Boston', 'Los Angeles'];
