import "dotenv/config";
import mongoose from "mongoose";
import { Job } from "./src/models/job.models.js";
import { Branch } from "./src/models/branch.models.js";
import { User } from "./src/models/user.models.js";

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
   

console.log("DB NAME:", mongoose.connection.name);
    console.log("✅ Connected to MongoDB");

    // Create or get branches
    let branches = await Branch.find();
    if (branches.length === 0) {
      console.log("📍 Creating sample branches...");
      const branchData = [
        { branchName: "New York" },
        { branchName: "Los Angeles" },
        { branchName: "Chicago" },
      ];
      branches = await Branch.insertMany(branchData);
      console.log(`✅ Created ${branches.length} branches`);
    } else {
      console.log(`✅ Found ${branches.length} existing branches`);
    }

    // Create or get admin user
    let adminUser = await User.findOne({ role: "admin" });
    if (!adminUser) {
      console.log("👤 Creating sample admin user...");
      adminUser = await User.create({
        name: "Admin User",
        email: "admin@example.com",
        password: "password123",
        role: "admin",
        isVerified: true,
      });
      console.log("✅ Created admin user");
    } else {
      console.log("✅ Found existing admin user");
    }

    // Create sample jobs
    const existingJobs = await Job.countDocuments();
    if (existingJobs === 0) {
      console.log("💼 Creating sample jobs...");
      
      const sampleJobs = [
        {
          branchId: branches[0]._id,
          title: "Senior Software Engineer",
          company: "Tech Corp",
          description: "Looking for an experienced software engineer with 5+ years of experience in full-stack development.",
          location: "New York, NY",
          department: "Engineering",
          category: "Engineering",
          type: "Full Time",
          salary: "$120,000 - $150,000",
          salaryNumeric: 135000,
          experience: "5+ Years",
          degree: "Bachelor's Degree",
          seats: 3,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "Product Manager",
          company: "Tech Corp",
          description: "Join our product team to shape the future of our platform.",
          location: "New York, NY",
          department: "Product",
          category: "Operations",
          type: "Full Time",
          salary: "$100,000 - $130,000",
          salaryNumeric: 115000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "Sales Executive",
          company: "Sales Corp",
          description: "Drive revenue growth by selling our enterprise solutions to Fortune 500 companies.",
          location: "New York, NY",
          department: "Sales",
          category: "Sales",
          type: "Full Time",
          salary: "$60,000 - $90,000",
          salaryNumeric: 75000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 4,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "Marketing Manager",
          company: "Brand Studios",
          description: "Lead our marketing initiatives and brand development in the New York region.",
          location: "New York, NY",
          department: "Marketing",
          category: "Marketing",
          type: "Full Time",
          salary: "$80,000 - $110,000",
          salaryNumeric: 95000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "Financial Analyst",
          company: "Finance Plus",
          description: "Analyze financial data and provide insights for strategic business planning.",
          location: "New York, NY",
          department: "Finance",
          category: "Finance",
          type: "Full Time",
          salary: "$70,000 - $100,000",
          salaryNumeric: 85000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "HR Specialist",
          company: "People First",
          description: "Support recruitment and employee management activities.",
          location: "New York, NY",
          department: "Human Resources",
          category: "HR",
          type: "Full Time",
          salary: "$50,000 - $70,000",
          salaryNumeric: 60000,
          experience: "1+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "UX/UI Designer",
          company: "Design Studios",
          description: "Create beautiful and intuitive user interfaces for our web and mobile applications.",
          location: "Los Angeles, CA",
          department: "Design",
          category: "Operations",
          type: "Full Time",
          salary: "$80,000 - $110,000",
          salaryNumeric: 95000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "Marketing Specialist",
          company: "Growth Co",
          description: "Drive marketing initiatives and campaigns to grow our business.",
          location: "Los Angeles, CA",
          department: "Marketing",
          category: "Marketing",
          type: "Full Time",
          salary: "$70,000 - $90,000",
          salaryNumeric: 80000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "Frontend Developer",
          company: "Web Solutions",
          description: "Build responsive and performant user interfaces using React and modern web technologies.",
          location: "Los Angeles, CA",
          department: "Engineering",
          category: "Engineering",
          type: "Full Time",
          salary: "$90,000 - $130,000",
          salaryNumeric: 110000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "Account Executive",
          company: "Enterprise Sales",
          description: "Manage key client relationships and drive sales growth for enterprise accounts.",
          location: "Los Angeles, CA",
          department: "Sales",
          category: "Sales",
          type: "Full Time",
          salary: "$75,000 - $120,000",
          salaryNumeric: 97500,
          experience: "4+ Years",
          degree: "Bachelor's Degree",
          seats: 3,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "Operations Manager",
          company: "Logistics Inc",
          description: "Oversee operational activities and ensure efficient processes.",
          location: "Los Angeles, CA",
          department: "Operations",
          category: "Operations",
          type: "Full Time",
          salary: "$65,000 - $95,000",
          salaryNumeric: 80000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "Data Analyst",
          company: "Analytics Inc",
          description: "Analyze data and provide insights to support business decisions.",
          location: "Chicago, IL",
          department: "Analytics",
          category: "Operations",
          type: "Full Time",
          salary: "$75,000 - $100,000",
          salaryNumeric: 87500,
          experience: "1+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "HR Manager",
          company: "People Solutions",
          description: "Manage human resources operations and employee relations.",
          location: "Chicago, IL",
          department: "HR",
          category: "HR",
          type: "Full Time",
          salary: "$65,000 - $85,000",
          salaryNumeric: 75000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "Backend Engineer",
          company: "Cloud Systems",
          description: "Design and develop scalable backend systems using Node.js and cloud technologies.",
          location: "Chicago, IL",
          department: "Engineering",
          category: "Engineering",
          type: "Full Time",
          salary: "$100,000 - $140,000",
          salaryNumeric: 120000,
          experience: "4+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "Business Analyst",
          company: "Consulting Group",
          description: "Analyze business requirements and provide strategic recommendations.",
          location: "Chicago, IL",
          department: "Business",
          category: "Operations",
          type: "Full Time",
          salary: "$70,000 - $100,000",
          salaryNumeric: 85000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "Sales Representative",
          company: "Direct Sales",
          description: "Develop and maintain client relationships while achieving sales targets.",
          location: "Chicago, IL",
          department: "Sales",
          category: "Sales",
          type: "Full Time",
          salary: "$55,000 - $85,000",
          salaryNumeric: 70000,
          experience: "1+ Years",
          degree: "High School Diploma",
          seats: 5,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[2]._id,
          title: "Finance Manager",
          company: "Financial Services",
          description: "Manage financial planning and budgeting activities for the region.",
          location: "Chicago, IL",
          department: "Finance",
          category: "Finance",
          type: "Full Time",
          salary: "$85,000 - $120,000",
          salaryNumeric: 102500,
          experience: "5+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[0]._id,
          title: "Full Stack Developer",
          company: "Tech Innovations",
          description: "Develop full-stack applications with modern technologies.",
          location: "New York, NY",
          department: "Engineering",
          category: "Engineering",
          type: "Full Time",
          salary: "$95,000 - $135,000",
          salaryNumeric: 115000,
          experience: "3+ Years",
          degree: "Bachelor's Degree",
          seats: 2,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
        {
          branchId: branches[1]._id,
          title: "Content Manager",
          company: "Digital Media",
          description: "Create and manage engaging content for multiple platforms.",
          location: "Los Angeles, CA",
          department: "Content",
          category: "Marketing",
          type: "Full Time",
          salary: "$60,000 - $80,000",
          salaryNumeric: 70000,
          experience: "2+ Years",
          degree: "Bachelor's Degree",
          seats: 1,
          status: "open",
          isActive: true,
          createdBy: adminUser._id,
        },
      ];

      await Job.insertMany(sampleJobs);
      console.log(`✅ Created ${sampleJobs.length} sample jobs`);
    } else {
      console.log(`✅ Database already has ${existingJobs} jobs`);
    }

    console.log("\n🎉 Database seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding database:", error.message);
    process.exit(1);
  }
};

seedDatabase();
